export const SUBSIDIARIES = [
  { id: 1, name: "Yanolja Cloud Pte. Ltd.",        shortName: "Yanolja Cloud",         searchKey: "Yanolja Cloud",         country: "Singapore",     active: true, kiprisSearchKey: "야놀자 클라우드",                            euipoSearchKey: "Yanolja Cloud Pte" },
  { id: 2, name: "Go Global Travel Ltd.",           shortName: "Go Global Travel",      searchKey: "Go Global Travel",      country: "Israel",        active: true,                                                         euipoSearchKey: "Go Global Travel" },
  { id: 3, name: "Yanolja Co., Ltd.",               shortName: "Yanolja",               searchKey: "Yanolja",               country: "South Korea",   active: true, kiprisSearchKey: "야놀자", kiprisUsSearchKey: "Yanolja",  euipoSearchKey: "Yanolja Co" },
  { id: 4, name: "Yanolja Cloud Solution PVT Ltd.", shortName: "YCS India",             searchKey: "Yanolja Cloud Solution", country: "India",        active: true,                                                         euipoSearchKey: "Yanolja Cloud Solution" },
  { id: 5, name: "Nol Universe Co., Ltd.",          shortName: "Nol Universe",          searchKey: "Nol Universe",          country: "South Korea",   active: true, kiprisSearchKey: "놀유니버스",                               euipoSearchKey: "Nol Universe" },
  { id: 6, name: "MST TRAVEL LTD.",                 shortName: "MST Travel",            searchKey: "MST TRAVEL",            country: "Israel",        active: true,                                                         euipoSearchKey: "MST TRAVEL" },
  { id: 7, name: "RightRez, Inc.",                  shortName: "RightRez",              searchKey: "RightRez",              country: "United States", active: true, kiprisUsSearchKey: "RightRez",                             euipoSearchKey: "RightRez" },
  { id: 8, name: "Innsoft, Inc.",                   shortName: "Innsoft",               searchKey: "Innsoft",               country: "United States", active: true, kiprisUsSearchKey: "Innsoft",                              euipoSearchKey: "Innsoft" },
];
